### ISSUE TITLE
Console Changes not working properly

### ISSUE THREAD

**Issue by Tiphk** [Tiphk/Project-1-Tiphaine-Kachkachi-CDOF3#2]
The main.js script calls the intro.js script.
When this happens, the output of intro.js are written in the console of main.js. When the user types something in the console, it displays the answer in the console of main.js. But we need to send the information into the intro.js as well to execute the following code.
Please note that when the script intro.js is launched seperatly from main.js, everything works just fine.

**Comment by RinjieMX** [comment]
To find the problem i tried to simplify the code to narrow down the code to look through. I created a separate main.js and a test.js file to test the connection between the 2 files. I called the test inside the new main to see if i could write in the console and send the information to the test.js file. There was an issue caused by too many async function so i changed the base of the ask.question function for the user. Instead of using 
ask1.question("", async (number) => {
//logic here
}); 
which was not working well i used a try/catch and a seperate new askFunction function to create an input field for the user.
